from midiutil import MIDIFile

track    = 0
channel  = 0
duration = 1
volume   = 100
tempo    = 200
MyMIDI = MIDIFile(1)
MyMIDI.addTempo(track, 0, tempo)
MyMIDI.addProgramChange(track, channel, 0, 30)
MyMIDI.addNote(track, channel,62,0, duration, volume)
MyMIDI.addNote(track, channel,74,1, duration, volume)
MyMIDI.addNote(track, channel,69,2, duration, volume)
MyMIDI.addNote(track, channel,67,3, duration, volume)
MyMIDI.addNote(track, channel,79,4, duration, volume)
MyMIDI.addNote(track, channel,69,5, duration, volume)
MyMIDI.addNote(track, channel,78,6, duration, volume)
MyMIDI.addNote(track, channel,69,7, duration, volume)
MyMIDI.addNote(track, channel,62,8, duration, volume)
MyMIDI.addNote(track, channel,74,9, duration, volume)
MyMIDI.addNote(track, channel,69,10, duration, volume)
MyMIDI.addNote(track, channel,67,11, duration, volume)
MyMIDI.addNote(track, channel,79,12, duration, volume)
MyMIDI.addNote(track, channel,69,13, duration, volume)
MyMIDI.addNote(track, channel,78,14, duration, volume)
MyMIDI.addNote(track, channel,69,15, duration, volume)
MyMIDI.addNote(track, channel,64,16, duration, volume)
MyMIDI.addNote(track, channel,74,17, duration, volume)
MyMIDI.addNote(track, channel,69,18, duration, volume)
MyMIDI.addNote(track, channel,67,19, duration, volume)
MyMIDI.addNote(track, channel,79,20, duration, volume)
MyMIDI.addNote(track, channel,69,21, duration, volume)
MyMIDI.addNote(track, channel,78,22, duration, volume)
MyMIDI.addNote(track, channel,69,23, duration, volume)
MyMIDI.addNote(track, channel,64,24, duration, volume)
MyMIDI.addNote(track, channel,74,25, duration, volume)
MyMIDI.addNote(track, channel,69,26, duration, volume)
MyMIDI.addNote(track, channel,67,27, duration, volume)
MyMIDI.addNote(track, channel,79,28, duration, volume)
MyMIDI.addNote(track, channel,69,29, duration, volume)
MyMIDI.addNote(track, channel,78,30, duration, volume)
MyMIDI.addNote(track, channel,69,31, duration, volume)
MyMIDI.addNote(track, channel,67,32, duration, volume)
MyMIDI.addNote(track, channel,74,33, duration, volume)
MyMIDI.addNote(track, channel,69,34, duration, volume)
MyMIDI.addNote(track, channel,67,35, duration, volume)
MyMIDI.addNote(track, channel,79,36, duration, volume)
MyMIDI.addNote(track, channel,69,37, duration, volume)
MyMIDI.addNote(track, channel,78,38, duration, volume)
MyMIDI.addNote(track, channel,69,39, duration, volume)
MyMIDI.addNote(track, channel,67,40, duration, volume)
MyMIDI.addNote(track, channel,74,41, duration, volume)
MyMIDI.addNote(track, channel,69,42, duration, volume)
MyMIDI.addNote(track, channel,67,43, duration, volume)
MyMIDI.addNote(track, channel,79,44, duration, volume)
MyMIDI.addNote(track, channel,69,45, duration, volume)
MyMIDI.addNote(track, channel,78,46, duration, volume)
MyMIDI.addNote(track, channel,69,47, duration, volume)
MyMIDI.addNote(track, channel,62,48, duration, volume)
MyMIDI.addNote(track, channel,74,49, duration, volume)
MyMIDI.addNote(track, channel,69,50, duration, volume)
MyMIDI.addNote(track, channel,67,51, duration, volume)
MyMIDI.addNote(track, channel,79,52, duration, volume)
MyMIDI.addNote(track, channel,69,53, duration, volume)
MyMIDI.addNote(track, channel,78,54, duration, volume)
MyMIDI.addNote(track, channel,69,55, duration, volume)
MyMIDI.addNote(track, channel,62,56, duration, volume)
MyMIDI.addNote(track, channel,74,57, duration, volume)
MyMIDI.addNote(track, channel,69,58, duration, volume)
MyMIDI.addNote(track, channel,67,59, duration, volume)
MyMIDI.addNote(track, channel,79,60, duration, volume)
MyMIDI.addNote(track, channel,69,61, duration, volume)
MyMIDI.addNote(track, channel,78,62, duration, volume)
MyMIDI.addNote(track, channel,69,63, duration, volume)
archivoMIDI = open('sweet.mid','wb')
MyMIDI.writeFile(archivoMIDI)